### ISSUE TITLE
Moving the Arduino motor to open door if the Mask is detected

### ISSUE THREAD

**Issue by Jaz0206** [chandrikadeb7/Face-Mask-Detection#55]
I want to put hands on to open door at entrance if a person is wearing mask

**Comment by BhendiBoi** [comment]
I am new to github and have barely any knowledge about python. i know this issue is closed, but you could find a way to get the results of the detect_mask_video.py program and then send the result to the arduino board via the serial monitor with the pyserial module. for information on the module this should suffice. https://www.youtube.com/watch?v=iKGYbMD3NT8
